/**
 * Agent service — Architecture (lib/services/agents/architecture.ts)
 *
 * Orchestrates the Architecture & Integration Agent, which answers sprint-
 * planning questions about microservice design, database selection, and
 * downstream dependencies within QE Savings Lab.
 *
 * ACADEMIC REQUIREMENT — Input and Output:
 *   INPUT:  ArchitectureInput containing the engineer's question and optional
 *           supplementary context. The useKnowledgeBase flag instructs the
 *           API route to load the internal knowledge base from disk before
 *           calling this service (RAG pattern — see the API route file).
 *   OUTPUT: ArchitectureRecord — wraps the AI answer (summary, answer,
 *           impactedComponents, integrationRisks, testImplications, etc.)
 *           with full governance metadata.
 *
 * ACADEMIC REQUIREMENT — Data Retrieval:
 *   Two storage operations are performed:
 *   1. writeRecord()   — persists the ArchitectureRecord to disk
 *   2. readRecord()    — exposed via getArchitectureRecord() for the review
 *                        and history pages to retrieve records by ID
 *   The audit event metadata also records whether the knowledge base was
 *   used, the number of impacted components identified, and the number of
 *   integration risks — enabling comparison between knowledge-base-assisted
 *   and unassisted responses over time.
 *
 * ACADEMIC REQUIREMENT — Variety in data structures:
 *   Tags are generated by taking the first word of each impacted component
 *   name (e.g. "Payment Processing Service" → "payment"), lowercasing it,
 *   and limiting to 5 tags. This demonstrates array transformation using
 *   .map(), .slice(), and the spread operator on a single line.
 */

import { writeRecord, readRecord } from '@/lib/storage'
import { generateId, generateTitle, now } from '@/lib/utils'
import { getProvider } from '@/lib/providers'
import { logAuditEvent } from '@/lib/services/audit'
import { buildArchitecturePrompt } from '@/lib/prompts/architecture'
import type { ArchitectureInput, ArchitectureRecord } from '@/types'

export async function runArchitectureAgent(
  input: ArchitectureInput,
  actor: string
): Promise<ArchitectureRecord> {
  // Resolve the active provider at runtime (gemini | mock | vertex)
  const provider = getProvider()

  // Build the prompt for audit logging — the provider may ignore it if mock,
  // but capturing it here ensures every request has a traceable prompt record
  const prompt = buildArchitecturePrompt(input)

  // Call the provider — returns a fully typed ArchitectureOutput
  const output = await provider.analyzeArchitecture(input)

  // Tags are derived from the impacted components array: take the first word
  // of each component name, lowercase it, and limit to 5 tags.
  // e.g. ['Payment Processing Service', 'Core Banking Ledger']
  //    → ['payment', 'core']
  const record: ArchitectureRecord = {
    id: generateId('arch'),              // e.g. 'arch_a1b2c3d4e5f6'
    title: generateTitle('architecture', input as unknown as Record<string, unknown>),
    agentType: 'architecture',
    status: 'draft',                     // awaiting human review before sharing with the team
    createdAt: now(),
    updatedAt: now(),
    createdBy: actor,
    linkedIds: [],
    tags: [
      // Array transformation: map component names to lowercase first-word tags
      ...output.impactedComponents.slice(0, 3).map((c) => c.split(' ')[0].toLowerCase()),
    ].slice(0, 5),
    input,   // preserved so the question and context are visible in the review UI
    output,  // AI-generated architecture analysis
  }

  // Persist to disk — data/outputs/arch_{id}.json
  writeRecord<ArchitectureRecord>('outputs', record)

  // Audit metadata captures whether the knowledge base was used, allowing
  // future analysis of whether RAG-assisted answers differ in quality or scope
  logAuditEvent({
    eventType: 'created',
    itemId: record.id,
    itemTitle: record.title,
    agentType: 'architecture',
    actor,
    details: `Architecture analysis generated by ${actor} using ${process.env.AI_PROVIDER ?? 'mock'} provider`,
    metadata: {
      promptLength: prompt.length,
      impactedComponentsCount: output.impactedComponents.length,
      integrationRisksCount: output.integrationRisks.length,
      usedKnowledgeBase: input.useKnowledgeBase ?? false,  // flags whether RAG was active
    },
  })

  return record
}

// getArchitectureRecord is the READ operation for this agent type.
// Returns null if the record does not exist, allowing callers to handle
// missing records gracefully without throwing.
export function getArchitectureRecord(id: string): ArchitectureRecord | null {
  return readRecord<ArchitectureRecord>('outputs', id)
}
