/**
 * Agent service — Automation (lib/services/agents/automation.ts)
 *
 * Orchestrates the Automation Agent, which takes Gherkin BDD scenarios and
 * produces Playwright TypeScript step definitions and Page Object classes.
 *
 * ACADEMIC REQUIREMENT — Input and Output:
 *   INPUT:  AutomationInput containing gherkinText and optional framework
 *           context, passed directly to the provider after Zod validation
 *           at the API route level.
 *   OUTPUT: AutomationRecord — wraps the AI-generated stepDefinitions,
 *           pageObjects, locators, warnings, and fullCode with governance
 *           metadata (id, status, actor, timestamps).
 *
 * ACADEMIC REQUIREMENT — Data Retrieval:
 *   This service performs three distinct storage operations:
 *   1. writeRecord()  — persists the new AutomationRecord to disk
 *   2. readRecord()   — retrieves the linked TestDesignRecord (if a
 *                       linkedTestDesignId was provided) so its linkedIds
 *                       array can be updated with the new automation record ID
 *   3. updateRecord() — writes the updated linkedIds back to the TestDesign
 *                       record, creating a bidirectional traceability link
 *
 * This traceability link is a key governance feature: it allows the QE team
 * to navigate from a test design to its automation implementation and back,
 * maintaining a complete audit trail across the testing lifecycle.
 */

import { writeRecord, updateRecord, readRecord } from '@/lib/storage'
import { generateId, generateTitle, now } from '@/lib/utils'
import { getProvider } from '@/lib/providers'
import { logAuditEvent } from '@/lib/services/audit'
import { buildAutomationPrompt } from '@/lib/prompts/automation'
import type { AutomationInput, AutomationRecord } from '@/types'

export async function runAutomationAgent(
  input: AutomationInput,
  actor: string
): Promise<AutomationRecord> {
  // Resolve the active provider at runtime (gemini | mock | vertex)
  const provider = getProvider()

  // Build the prompt for audit logging — captured regardless of provider mode
  const prompt = buildAutomationPrompt(input)

  // Call the provider — returns a fully typed AutomationOutput
  const output = await provider.generateAutomationDraft(input)

  // Assemble the AutomationRecord — status starts as 'draft'.
  // linkedIds is populated immediately if the engineer linked this run to an
  // existing test design, establishing forward traceability at creation time.
  const record: AutomationRecord = {
    id: generateId('au'),                // e.g. 'au_a1b2c3d4e5f6'
    title: generateTitle('automation', input as unknown as Record<string, unknown>),
    agentType: 'automation',
    status: 'draft',                     // awaiting human review before use
    createdAt: now(),
    updatedAt: now(),
    createdBy: actor,
    linkedIds: input.linkedTestDesignId ? [input.linkedTestDesignId] : [],
    tags: [],                            // automation records derive tags from linked test design
    input,
    output,
  }

  // ACADEMIC REQUIREMENT — Data Retrieval (write):
  // Persist the new automation record to data/outputs/au_{id}.json
  writeRecord<AutomationRecord>('outputs', record)

  // ACADEMIC REQUIREMENT — Data Retrieval (read + update):
  // If this automation was linked to an existing test design, read that record
  // from disk and append this record's ID to its linkedIds array.
  // This creates bidirectional traceability: the test design knows about its
  // automation, and the automation knows about its test design.
  if (input.linkedTestDesignId) {
    const linked = readRecord<{ id: string; linkedIds: string[] }>('outputs', input.linkedTestDesignId)
    if (linked) {
      // Merge the new ID into the existing linkedIds array using spread
      updateRecord<{ id: string; linkedIds: string[]; updatedAt?: string }>('outputs', input.linkedTestDesignId, {
        linkedIds: [...(linked.linkedIds ?? []), record.id],
        updatedAt: now(),
      })
      // Log a separate 'linked' audit event for the traceability connection
      logAuditEvent({
        eventType: 'linked',
        itemId: record.id,
        itemTitle: record.title,
        agentType: 'automation',
        actor,
        details: `Linked to Test Design: ${input.linkedTestDesignId}`,
      })
    }
  }

  // Log the creation audit event with metadata useful for analysis:
  // promptLength confirms the model received full context,
  // stepCount records how many step definitions were generated
  logAuditEvent({
    eventType: 'created',
    itemId: record.id,
    itemTitle: record.title,
    agentType: 'automation',
    actor,
    details: `Automation draft generated by ${actor} using ${process.env.AI_PROVIDER ?? 'mock'} provider`,
    metadata: { promptLength: prompt.length, stepCount: output.stepDefinitions.length },
  })

  return record
}
