/**
 * Agent service — Failure Analysis (lib/services/agents/failure-analysis.ts)
 *
 * Orchestrates the Failure Analysis Agent, which classifies a Playwright test
 * failure and produces a structured triage report with a Jira-ready defect note.
 *
 * ACADEMIC REQUIREMENT — Input and Output:
 *   INPUT:  FailureAnalysisInput containing the scenario name and failed log
 *           (mandatory), plus optional stack trace, screenshot notes, and
 *           environment notes. Richer context produces more accurate output.
 *   OUTPUT: FailureAnalysisRecord — wraps the AI classification (failureCategory,
 *           confidenceLevel, rootCause, draftDefectNote) with governance
 *           metadata. The status starts as 'draft'; a human must review and
 *           approve the triage before the defect note is raised in Jira.
 *
 * ACADEMIC REQUIREMENT — Variety in data structures:
 *   Tags are derived dynamically from the AI output at record creation time:
 *   - output.failureCategory  → one of the five FailureCategory enum values
 *   - output.confidenceLevel  → High | Medium | Low, lowercased for tagging
 *   This produces tags like ['real-defect', 'high'] or ['flaky', 'medium'],
 *   which the history view uses to filter and group failure analysis records.
 *
 * ACADEMIC REQUIREMENT — Data Retrieval:
 *   writeRecord() persists the record to data/outputs/fa_{id}.json.
 *   The audit event metadata captures the failure category and confidence
 *   level, enabling future analysis of classification patterns over time.
 */

import { writeRecord } from '@/lib/storage'
import { generateId, now } from '@/lib/utils'
import { getProvider } from '@/lib/providers'
import { logAuditEvent } from '@/lib/services/audit'
import { buildFailureAnalysisPrompt } from '@/lib/prompts/failure-analysis'
import type { FailureAnalysisInput, FailureAnalysisRecord } from '@/types'

export async function runFailureAnalysisAgent(
  input: FailureAnalysisInput,
  actor: string
): Promise<FailureAnalysisRecord> {
  // Resolve the active provider at runtime (gemini | mock | vertex)
  const provider = getProvider()

  // Build the prompt — captured for audit metadata even in mock mode
  const prompt = buildFailureAnalysisPrompt(input)

  // Call the provider — returns a fully typed FailureAnalysisOutput
  const output = await provider.analyzeFailure(input)

  // Assemble the record. Tags are derived from the AI output so the record
  // can be filtered by failure type and confidence in the history view
  // without needing to open the full record.
  const record: FailureAnalysisRecord = {
    id: generateId('fa'),               // e.g. 'fa_a1b2c3d4e5f6'
    title: `FA: ${input.scenarioName} [${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}]`,
    agentType: 'failure-analysis',
    status: 'draft',                    // awaiting human review before Jira ticket is raised
    createdAt: now(),
    updatedAt: now(),
    createdBy: actor,
    linkedIds: input.linkedTestDesignId ? [input.linkedTestDesignId] : [],
    // Tags derived from AI output — failureCategory and lowercased confidence level
    // e.g. ['real-defect', 'high'] or ['flaky', 'medium']
    tags: [output.failureCategory, output.confidenceLevel.toLowerCase()],
    input,   // original failure log preserved for re-analysis or audit
    output,  // AI-generated triage report
  }

  // Persist to disk — data/outputs/fa_{id}.json
  writeRecord<FailureAnalysisRecord>('outputs', record)

  // Audit event metadata includes category and confidence so classification
  // trends can be analysed across the audit log over time
  logAuditEvent({
    eventType: 'created',
    itemId: record.id,
    itemTitle: record.title,
    agentType: 'failure-analysis',
    actor,
    details: `Failure analysis generated by ${actor} using ${process.env.AI_PROVIDER ?? 'mock'} provider`,
    metadata: {
      promptLength: prompt.length,
      category: output.failureCategory,     // e.g. 'real-defect'
      confidence: output.confidenceLevel,   // e.g. 'High'
    },
  })

  return record
}
