/**
 * Agent service — Test Design (lib/services/agents/test-design.ts)
 *
 * This module orchestrates the complete execution of the Test Design Agent.
 * It sits between the API route (which handles HTTP concerns) and the
 * individual library modules (prompts, providers, storage, audit).
 *
 * ACADEMIC REQUIREMENT — Input and Output:
 *   runTestDesignAgent() takes a validated TestDesignInput and returns a
 *   fully populated TestDesignRecord. The record is the primary OUTPUT of
 *   the agent — it contains the AI-generated content (output), the original
 *   input (input), and all governance metadata (status, actor, timestamps).
 *
 * ACADEMIC REQUIREMENT — Data Retrieval:
 *   Two storage operations are performed:
 *   - writeRecord() persists the new record to data/outputs/{id}.json
 *   - appendAuditEvent() (via logAuditEvent) persists an immutable audit
 *     entry to data/audit/{id}.json
 *   getTestDesignRecord() demonstrates READ retrieval — it reads a single
 *   record back from disk by ID, used by the review and approval pages.
 *
 * Execution flow:
 *   1. Resolve the active AI provider via getProvider()
 *   2. Build the prompt string (also captured for audit metadata)
 *   3. Call the provider to get the AI-generated output
 *   4. Assemble the full TestDesignRecord with metadata
 *   5. Persist the record to disk
 *   6. Log an audit event recording who triggered this and what was produced
 *   7. Return the record to the API route
 */

import { writeRecord, readRecord } from '@/lib/storage'
import { generateId, generateTitle, now } from '@/lib/utils'
import { getProvider } from '@/lib/providers'
import { logAuditEvent } from '@/lib/services/audit'
import { buildTestDesignPrompt } from '@/lib/prompts/test-design'
import type { TestDesignInput, TestDesignRecord } from '@/types'

export async function runTestDesignAgent(
  input: TestDesignInput,
  actor: string
): Promise<TestDesignRecord> {
  // Resolve the active provider at runtime (gemini | mock | vertex)
  const provider = getProvider()

  // Build the prompt even in mock mode — the prompt length is recorded in
  // the audit event so reviewers can verify the model received full context
  const prompt = buildTestDesignPrompt(input)

  // Call the provider — returns a fully typed TestDesignOutput
  const output = await provider.generateTestDesign(input)

  // Assemble the record: combines the AI output with governance metadata.
  // Status starts as 'draft' — it cannot be used until a human approves it.
  // Tags are derived from the AI output (priorityTags + riskTags) and stored
  // on the record for filtering and searching in the history view.
  const record: TestDesignRecord = {
    id: generateId('td'),                // e.g. 'td_a1b2c3d4e5f6'
    title: generateTitle('test-design', input as unknown as Record<string, unknown>),
    agentType: 'test-design',
    status: 'draft',                     // initial state — awaiting human review
    createdAt: now(),
    updatedAt: now(),
    createdBy: actor,
    linkedIds: [],                       // populated later if linked to an automation record
    tags: [...output.priorityTags, ...output.riskTags].slice(0, 5),
    input,                               // preserved for audit and re-run purposes
    output,                              // the AI-generated content
  }

  // Persist to disk — data/outputs/td_a1b2c3d4e5f6.json
  writeRecord<TestDesignRecord>('outputs', record)

  // Write an immutable audit event recording who created this, with which
  // provider, how long the prompt was, and how many scenarios were generated
  logAuditEvent({
    eventType: 'created',
    itemId: record.id,
    itemTitle: record.title,
    agentType: 'test-design',
    actor,
    details: `Test design generated by ${actor} using ${process.env.AI_PROVIDER ?? 'mock'} provider`,
    metadata: { promptLength: prompt.length, scenarioCount: output.scenarios.length },
  })

  return record
}

// getTestDesignRecord is the READ operation for this agent type.
// Returns null if the record does not exist, rather than throwing —
// allowing callers to handle missing records gracefully.
export function getTestDesignRecord(id: string): TestDesignRecord | null {
  return readRecord<TestDesignRecord>('outputs', id)
}
