/**
 * Confluence Export API Route
 *
 * POST /api/confluence-export
 *
 * Creates a Confluence page from a test plan selection.
 * Returns the new page URL.
 *
 * Requires in .env.local:
 *   CONFLUENCE_BASE_URL   https://yourcompany.atlassian.net/wiki
 *   CONFLUENCE_EMAIL      your.email@company.com
 *   CONFLUENCE_API_TOKEN  your_api_token
 *   CONFLUENCE_SPACE_KEY  QE  (default space to publish into)
 */

import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

// ─── Validation ───────────────────────────────────────────────────────────────

const ScenarioSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string(),
  priority: z.enum(['High', 'Medium', 'Low']),
  type: z.string(),
  tags: z.array(z.string()),
})

const GherkinSchema = z.object({
  id: z.string(),
  title: z.string(),
  tags: z.array(z.string()),
  steps: z.string(),
})

const ExportSchema = z.object({
  pageTitle: z.string().min(1),
  spaceKey: z.string().min(1),
  parentPageId: z.string().optional(),
  storyTitle: z.string(),
  scenarios: z.array(ScenarioSchema),
  gherkin: z.array(GherkinSchema),
  edgeCases: z.array(z.string()),
  negativeCases: z.array(z.string()),
})

// ─── Confluence Storage Format (XHTML) builder ───────────────────────────────

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function buildConfluencePage(data: z.infer<typeof ExportSchema>): string {
  const parts: string[] = []

  parts.push(`<p><em>Generated by <strong>AI QE Control Tower</strong> · QE Savings Lab · ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</em></p>`)
  parts.push(`<p><strong>Story:</strong> ${escapeXml(data.storyTitle)}</p>`)
  parts.push('<hr />')

  // ── Test Scenarios ──
  if (data.scenarios.length > 0) {
    parts.push(`<h2>Test Scenarios (${data.scenarios.length})</h2>`)
    parts.push('<table><tbody>')
    parts.push('<tr><th><strong>#</strong></th><th><strong>Title</strong></th><th><strong>Priority</strong></th><th><strong>Type</strong></th><th><strong>Description</strong></th><th><strong>Tags</strong></th></tr>')
    data.scenarios.forEach((s, i) => {
      const priorityColour = s.priority === 'High' ? '#FFBDAD' : s.priority === 'Medium' ? '#FFF0B3' : '#ABF5D1'
      parts.push(`<tr>
        <td>${i + 1}</td>
        <td><strong>${escapeXml(s.title)}</strong></td>
        <td><span style="background-color:${priorityColour};padding:2px 6px;border-radius:3px;">${s.priority}</span></td>
        <td>${escapeXml(s.type.replace('-', ' '))}</td>
        <td>${escapeXml(s.description)}</td>
        <td><code>${escapeXml(s.tags.join(' '))}</code></td>
      </tr>`)
    })
    parts.push('</tbody></table>')
  }

  // ── Gherkin Scenarios ──
  if (data.gherkin.length > 0) {
    parts.push(`<h2>Gherkin Scenarios (${data.gherkin.length})</h2>`)
    data.gherkin.forEach((g) => {
      parts.push(`<h3>${escapeXml(g.title)}</h3>`)
      if (g.tags.length > 0) {
        parts.push(`<p><code>${escapeXml(g.tags.join(' '))}</code></p>`)
      }
      parts.push(`<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">gherkin</ac:parameter><ac:plain-text-body><![CDATA[${g.steps}]]></ac:plain-text-body></ac:structured-macro>`)
    })
  }

  // ── Edge Cases ──
  if (data.edgeCases.length > 0) {
    parts.push(`<h2>Edge Cases (${data.edgeCases.length})</h2><ul>`)
    data.edgeCases.forEach((e) => parts.push(`<li>${escapeXml(e)}</li>`))
    parts.push('</ul>')
  }

  // ── Negative Cases ──
  if (data.negativeCases.length > 0) {
    parts.push(`<h2>Negative Cases (${data.negativeCases.length})</h2><ul>`)
    data.negativeCases.forEach((n) => parts.push(`<li>${escapeXml(n)}</li>`))
    parts.push('</ul>')
  }

  return parts.join('\n')
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const baseUrl = process.env.CONFLUENCE_BASE_URL?.replace(/\/$/, '')
  const email   = process.env.CONFLUENCE_EMAIL
  const token   = process.env.CONFLUENCE_API_TOKEN

  if (!baseUrl || !email || !token) {
    return NextResponse.json(
      { error: 'Confluence credentials not configured. Add CONFLUENCE_BASE_URL, CONFLUENCE_EMAIL, and CONFLUENCE_API_TOKEN to .env.local.' },
      { status: 503 }
    )
  }

  const auth = Buffer.from(`${email}:${token}`).toString('base64')

  try {
    const body = await req.json()
    const parsed = ExportSchema.safeParse(body)

    if (!parsed.success) {
      return NextResponse.json({ error: 'Invalid input', issues: parsed.error.flatten().fieldErrors }, { status: 400 })
    }

    const { pageTitle, spaceKey, parentPageId } = parsed.data
    const storageBody = buildConfluencePage(parsed.data)

    const payload: Record<string, unknown> = {
      title: pageTitle,
      type: 'page',
      space: { key: spaceKey },
      body: {
        storage: {
          value: storageBody,
          representation: 'storage',
        },
      },
    }
    if (parentPageId) {
      payload.ancestors = [{ id: parentPageId }]
    }

    const res = await fetch(`${baseUrl}/rest/api/content`, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${auth}`,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(15_000),
    })

    if (!res.ok) {
      let errorMsg = `HTTP ${res.status}`
      try {
        const errData = await res.json() as { message?: string }
        if (errData.message) errorMsg = errData.message
      } catch { /* ignore */ }
      return NextResponse.json({ error: errorMsg }, { status: res.status })
    }

    const data = await res.json() as { id: string; _links?: { webui?: string } }
    const pageUrl = data._links?.webui
      ? `${baseUrl}${data._links.webui}`
      : `${baseUrl}/pages/${data.id}`

    return NextResponse.json({ success: true, pageUrl, pageId: data.id })
  } catch (error) {
    console.error('[confluence-export] Error:', error)
    return NextResponse.json({ error: 'Failed to export to Confluence' }, { status: 500 })
  }
}
