/**
 * Domain type definitions — types/index.ts
 *
 * This file is the single source of truth for all TypeScript types and
 * interfaces used across the application. Centralising types here ensures
 * consistency between the API layer, service layer, storage layer, and UI —
 * a change to any interface is immediately surfaced as a compiler error in
 * every file that depends on it.
 *
 * ACADEMIC REQUIREMENT — Variety in data structures:
 * This file demonstrates a wide range of TypeScript data structures:
 *
 *   Discriminated union types  → AgentType, ItemStatus, Priority, ScenarioType,
 *                                ConfidenceLevel, FailureCategory, ExportFormat
 *   Interfaces with optional fields → TestDesignInput (businessNotes?, riskNotes?)
 *   Arrays of typed objects    → TestDesignOutput.scenarios: TestScenario[]
 *   Nested interfaces          → PageObjectSuggestion contains LocatorSuggestion[]
 *   Interface inheritance      → TestDesignRecord extends BaseOutputRecord
 *   Union of record types      → OutputRecord = TestDesignRecord | AutomationRecord | ...
 *   Mapped/generic types       → AuditEvent.metadata: Record<string, unknown>
 *   Numeric and boolean fields → DashboardStats.approvalRate: number
 *
 * The separation of Input, Output, and Record types for each agent is a
 * deliberate architectural decision:
 *   - Input types define what the engineer provides
 *   - Output types define what the AI model returns
 *   - Record types wrap both with governance metadata (status, actor, timestamps)
 *     so the system can track the full lifecycle of every AI-generated artefact
 */

// ─── Agent Types ──────────────────────────────────────────────────────────────
// AgentType is a discriminated union — a TypeScript pattern where a shared
// field ('agentType') on a set of interfaces allows the compiler to narrow
// the type automatically inside switch/if blocks. This is used in generateTitle()
// in lib/utils/index.ts and in the record interfaces below.

export type AgentType = 'test-design' | 'automation' | 'failure-analysis' | 'architecture'

// ItemStatus models the approval lifecycle state machine.
// A record may only ever hold one of these values, enforced at both the
// TypeScript level (compile time) and the Zod schema level (runtime).
export type ItemStatus =
  | 'draft'
  | 'pending-approval'
  | 'approved'
  | 'rejected'
  | 'returned'
  | 'exported'

// Priority and ScenarioType are constrained string unions used in test scenario
// objects. Restricting to a fixed set prevents the AI model's output from
// containing arbitrary strings that would break filtering and reporting logic.
export type Priority = 'High' | 'Medium' | 'Low'

export type ScenarioType =
  | 'happy-path'
  | 'edge-case'
  | 'negative'
  | 'boundary'
  | 'security'
  | 'performance'

// ─── Test Design ──────────────────────────────────────────────────────────────
// ACADEMIC REQUIREMENT — Input and Output:
// TestDesignInput is the INPUT to the Test Design Agent.
// TestDesignOutput is the OUTPUT returned by the AI model.
// The optional fields (businessNotes, riskNotes) allow engineers to provide
// supplementary context without making it mandatory to invoke the agent.

export interface TestDesignInput {
  storyText: string            // the user story in plain text
  acceptanceCriteria: string   // the formal AC from the ticket
  businessNotes?: string       // optional FCA/regulatory context
  riskNotes?: string           // optional known risk areas to prioritise
}

// TestScenario represents a single test case generated by the AI.
// The combination of priority, type, and tags allows the QE team to filter,
// sort, and select scenarios for inclusion in the approved test artefact.
export interface TestScenario {
  id: string
  title: string
  description: string
  priority: Priority           // High | Medium | Low
  type: ScenarioType           // happy-path | edge-case | negative | etc.
  tags: string[]               // e.g. ['@regression', '@smoke', '@priority-high']
}

// GherkinScenario holds the BDD scenario text in Cucumber/Gherkin format.
// Steps is a raw string (not a structured array) because Gherkin syntax
// has its own line-based grammar that is best preserved as-is for direct
// use in a Playwright BDD framework.
export interface GherkinScenario {
  id: string
  title: string
  tags: string[]
  steps: string // full gherkin text
}

// TestDesignOutput is the complete AI-generated test design artefact.
// It contains multiple data structure types: an array of typed objects
// (scenarios, gherkinScenarios), arrays of strings (edgeCases, negativeCases,
// priorityTags, riskTags, assumptions, questions), and a summary string.
export interface TestDesignOutput {
  summary: string
  scenarios: TestScenario[]
  gherkinScenarios: GherkinScenario[]
  edgeCases: string[]
  negativeCases: string[]
  priorityTags: string[]
  riskTags: string[]
  assumptions: string[]
  questions: string[]
}

// ─── Automation ───────────────────────────────────────────────────────────────
// AutomationInput is the INPUT to the Automation Agent.
// The linked fields (linkedTestDesignId) allow the system to trace an
// automation record back to the test design that originated it.

export interface AutomationInput {
  gherkinText: string
  frameworkNotes?: string           // existing framework conventions
  existingStepsContext?: string     // already-implemented steps to avoid duplication
  pageObjectContext?: string        // existing page object structure
  linkedTestDesignId?: string       // traceability back to source test design
}

// StepDefinition represents a single Cucumber step (Given/When/Then).
// The imports array lists the TypeScript modules the generated step requires,
// making it straightforward to drop the code into an existing framework.
export interface StepDefinition {
  id: string
  keyword: string    // Given / When / Then
  pattern: string    // the Cucumber step pattern, e.g. 'I enter {string}'
  implementation: string
  imports: string[]
}

// PageObjectSuggestion demonstrates nested data structures —
// it contains an array of LocatorSuggestion objects, each of which
// carries its own strategy and rationale fields.
export interface PageObjectSuggestion {
  name: string
  filePath: string
  locators: LocatorSuggestion[]  // nested array of typed objects
  methods: string[]
}

// LocatorSuggestion is shared between AutomationOutput and FailureAnalysisOutput,
// demonstrating interface reuse across agent types. The strategy field is a
// discriminated union that constrains the locator approach to Playwright-supported
// strategies, preventing the AI from suggesting invalid selector types.
export interface LocatorSuggestion {
  name: string
  strategy: 'data-testid' | 'role' | 'text' | 'label' | 'placeholder' | 'css' | 'xpath'
  value: string
  rationale: string  // explains why this strategy was chosen
}

export interface AutomationOutput {
  stepDefinitions: StepDefinition[]
  pageObjects: PageObjectSuggestion[]
  locators: LocatorSuggestion[]
  helperSuggestions: string[]
  implementationNotes: string[]
  warnings: string[]
  assumptions: string[]
  fullCode: string // consolidated code block ready for copy-paste
}

// ─── Failure Analysis ─────────────────────────────────────────────────────────
// FailureAnalysisInput is the INPUT to the Failure Analysis Agent.
// Only scenarioName and failedLog are required — the optional fields
// (stackTrace, screenshotNotes, etc.) improve classification accuracy
// but the agent can operate with minimal context.

export interface FailureAnalysisInput {
  scenarioName: string
  failedLog: string
  stackTrace?: string
  screenshotNotes?: string
  traceSummary?: string
  environmentNotes?: string
  linkedTestDesignId?: string
}

// ConfidenceLevel and FailureCategory are constrained union types that
// correspond to the Zod enum schemas in lib/schemas/index.ts.
// Using identical values in both the TypeScript type and the Zod schema
// ensures the compile-time and runtime contracts stay in sync.
export type ConfidenceLevel = 'High' | 'Medium' | 'Low'
export type FailureCategory = 'real-defect' | 'flaky' | 'environment' | 'test-code' | 'data-issue'

// FailureAnalysisOutput is the OUTPUT of the Failure Analysis Agent.
// It combines scalar fields (rootCause, draftDefectNote), enum fields
// (confidenceLevel, failureCategory), and arrays (suggestedNextActions,
// locatorRecommendations) — demonstrating variety in a single interface.
export interface FailureAnalysisOutput {
  summary: string
  rootCause: string
  confidenceLevel: ConfidenceLevel
  failureCategory: FailureCategory
  flakynessAssessment: string
  suggestedNextActions: string[]
  locatorRecommendations: LocatorSuggestion[]  // reused from Automation types
  draftDefectNote: string                       // Jira-ready markdown defect note
  escalationNotes: string
  relatedScenarios: string[]
}

// ─── Approval & Audit ─────────────────────────────────────────────────────────
// ApprovalRecord and AuditEvent together implement the human-in-the-loop
// governance model. Every AI output must be approved before use, and every
// state transition (submit, approve, reject, return) is recorded as an
// immutable AuditEvent — satisfying traceability requirements in a
// regulated financial services context.

export interface ApprovalComment {
  id: string
  author: string
  text: string
  timestamp: string
}

// ApprovalRecord tracks the review state of a single AI-generated output.
// reviewedAt and reviewedBy are optional because they are only populated
// once a reviewer has acted — they are absent while the record is in draft
// or pending-approval state.
export interface ApprovalRecord {
  id: string
  itemId: string
  itemTitle: string
  agentType: AgentType
  status: ItemStatus
  submittedAt: string
  submittedBy: string
  reviewedAt?: string       // populated on approve/reject/return
  reviewedBy?: string       // populated on approve/reject/return
  comments: ApprovalComment[]
}

// AuditEventType enumerates every action that can be recorded in the audit log.
// Using a union type rather than a plain string prevents typos and ensures
// the audit log contains only meaningful, queryable event names.
export type AuditEventType =
  | 'created'
  | 'submitted'
  | 'approved'
  | 'rejected'
  | 'returned'
  | 'edited'
  | 'exported'
  | 'linked'
  | 'seeded'

// AuditEvent is an immutable log entry. Once written to disk it is never
// updated — this provides a tamper-evident compliance trail.
// The metadata field uses Record<string, unknown> to allow any key-value
// pairs to be attached (e.g. promptLength, scenarioCount) without requiring
// a schema change for every new piece of contextual data.
export interface AuditEvent {
  id: string
  timestamp: string
  eventType: AuditEventType
  itemId: string
  itemTitle: string
  agentType: AgentType
  actor: string
  details: string
  metadata?: Record<string, unknown>   // open map for contextual data
}

// ─── Unified Output Record ────────────────────────────────────────────────────
// ACADEMIC REQUIREMENT — Variety in data structures:
// BaseOutputRecord is an abstract base interface (not exported directly) that
// captures the governance metadata common to every agent output. The four
// concrete record types extend it using interface inheritance, adding their
// specific input and output fields.
//
// This pattern avoids repeating id, title, status, createdAt, etc. in every
// record type, keeping the type definitions DRY and maintainable.

interface BaseOutputRecord {
  id: string
  title: string
  agentType: AgentType
  status: ItemStatus
  createdAt: string
  updatedAt: string
  createdBy: string
  approvedBy?: string      // populated when approved
  approvedAt?: string
  rejectedBy?: string      // populated when rejected
  rejectedAt?: string
  exportedAt?: string      // populated when exported
  linkedIds: string[]      // IDs of related records (e.g. automation linked to test design)
  tags: string[]           // derived from AI output for filtering and search
}

/**
 * Tracks which items the user has selected for export/approval.
 * Stored alongside the record so selections survive page refreshes.
 */
export interface TestDesignSelection {
  scenarioIds: string[]          // selected TestScenario.id values
  gherkinIds: string[]           // selected GherkinScenario.id values
  edgeCaseIndices: number[]      // selected indices in output.edgeCases[]
  negativeCaseIndices: number[]  // selected indices in output.negativeCases[]
}

// Each Record type extends BaseOutputRecord with its specific input/output pair.
// The editedOutput field (Partial<T>) allows a reviewer to make amendments
// to individual fields of the AI output without replacing it entirely —
// preserving both the original AI output and the human-edited version.
export interface TestDesignRecord extends BaseOutputRecord {
  agentType: 'test-design'
  input: TestDesignInput
  output: TestDesignOutput
  editedOutput?: Partial<TestDesignOutput>
  /** Items the user has chosen to include in the approved/exported artefact */
  selection?: TestDesignSelection
}

export interface AutomationRecord extends BaseOutputRecord {
  agentType: 'automation'
  input: AutomationInput
  output: AutomationOutput
  editedOutput?: Partial<AutomationOutput>
}

export interface FailureAnalysisRecord extends BaseOutputRecord {
  agentType: 'failure-analysis'
  input: FailureAnalysisInput
  output: FailureAnalysisOutput
  editedOutput?: Partial<FailureAnalysisOutput>
}

// ─── Architecture & Integration ───────────────────────────────────────────────

// ArchitectureInput includes useKnowledgeBase — a boolean flag that instructs
// the API route to load the internal knowledge base from disk and inject it
// into the prompt (RAG pattern). This is the primary data retrieval trigger
// in the Architecture Agent flow.
export interface ArchitectureInput {
  question: string
  architectureContext?: string
  servicesContext?: string
  downstreamNotes?: string
  modernisationNotes?: string
  useKnowledgeBase?: boolean     // triggers knowledge base retrieval when true
}

// ArchitectureOutput contains multiple string arrays that map directly to
// structured sections in the UI — impactedComponents, integrationRisks,
// testImplications, etc. Each array is independently renderable and filterable.
export interface ArchitectureOutput {
  summary: string
  answer: string
  impactedComponents: string[]
  integrationRisks: string[]
  testImplications: string[]
  assumptions: string[]
  missingInformation: string[]
  recommendedNextSteps: string[]
}

export interface ArchitectureRecord extends BaseOutputRecord {
  agentType: 'architecture'
  input: ArchitectureInput
  output: ArchitectureOutput
  editedOutput?: Partial<ArchitectureOutput>
}

// OutputRecord is a discriminated union of all four record types.
// Code that handles any record type (e.g. the history page, the export service)
// can use this single type and the compiler will enforce exhaustive handling
// of each agent type variant through the agentType discriminant field.
export type OutputRecord = TestDesignRecord | AutomationRecord | FailureAnalysisRecord | ArchitectureRecord

// ─── Dashboard ────────────────────────────────────────────────────────────────
// DashboardStats demonstrates a deeply nested object type — it contains
// scalar numbers (totalRequests, approvalRate), a nested object (byAgent,
// coverage), and arrays of typed objects (topRiskTags, recentActivity).
// This structure is assembled by the /api/dashboard route from aggregated
// storage queries and returned as a single JSON response.

export interface TagFrequency {
  tag: string
  count: number
}

export interface DashboardStats {
  totalRequests: number
  pendingApprovals: number
  approved: number
  rejected: number
  exported: number
  approvalRate: number          // percentage 0–100
  byAgent: {
    testDesign: number
    automation: number
    failureAnalysis: number
    architecture: number
  }
  coverage: {
    totalScenarios: number
    totalGherkin: number
    totalEdgeCases: number
    totalNegativeCases: number
    highPriority: number
    mediumPriority: number
    lowPriority: number
  }
  topRiskTags: TagFrequency[]
  topPriorityTags: TagFrequency[]
  recentActivity: AuditEvent[]
}

// ─── Export ───────────────────────────────────────────────────────────────────

export type ExportFormat = 'json' | 'markdown'

export interface ExportRecord {
  id: string
  itemId: string
  format: ExportFormat
  filename: string
  exportedAt: string
  exportedBy: string
}
